### PR TITLE
Added some HUCs!

### PR DESCRIPTION
**Pull request by bocinsky**
Hey Blake!

I made the updates I proposed in my email this morning, and added some code that processes the WBD in a prettier (and more info-rich) way. Sorry for using the magrittr pipe though! I also commented out your pretty colors on the map, just because I didn't want to deal with creating some new ones.

### CODE REVIEW

**Comment by kbvernon** [comment]
Awesome! Thanks, Kyle! I actually did a deep dive of [observable.js in Quarto](https://quarto.org/docs/interactive/ojs/) over the weekend and am almost to the point where I can add some interactive elements for watershed selection. It will also generate a complete list we can send to Josh at ArchSW. Fortunately, that's separate from getting the spatial data. How big is the geojson file now? Was trying to keep it below 5 MB for CI, hence the use of rmapshaper. 

And no worries about the pipe! If it works, it works.

**Comment by bocinsky** [comment]
It bumped up to 5.2 megs, but feel free to adjust down again. I just stuck with your ms_simplify call, but I didn't realize you'd tuned it to a specific size.

**Comment by bocinsky** [comment]
Also, I didn't re-knot the Quarto doc, in case you wanted to review the output before pushing a new html. Just FYI!

**Comment by kbvernon** [comment]
Ah, OK, yeah. 5.2 is probably ok (I'm no expert on git...). And, yeah, I can fiddle with the observable stuff a little more before updating the html. Thanks!

**Comment by bocinsky** [comment]
Map on my fork here <https://www.bocinsky.io/hndsr-watersheds/>

**Comment by kbvernon** [comment]
Oh. Right on. I guess I'm gonna have to dig into AWS now. That was one weak spot (afaik anyway) of the USGS ESRI REST, that it only allowed for downloads at the HUC12 level. Anyway, thanks again!

**Pull request merged**
